services:
  backend:
    restart: unless-stopped
    volumes:
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - .:/var/www/app
    networks:
      - todo-app
  nginx:
    image: nginx:1.17.3
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public/:/usr/share/nginx/todo-app:ro
    networks:
      - todo-app
    depends_on:
      - backend
    command: [nginx, "-g", "daemon off;"]
  storage:
    image: mariadb:10.2.29
    volumes:
      - persistent:/var/lib/mysql
      - ./docker/db/:/docker-entrypoint-initdb.d/
    networks:
      - todo-app

networks:
  todo-app:
    external: false
volumes:
  persistent:
