imports:
    - { resource: "../src/Storage/storage-services.yaml" }
    - { resource: "../src/Shared/shared-services.yaml" }
    - { resource: "../src/User/user-services.yaml" }
    - { resource: "../src/Auth/auth-services.yaml" }
    - { resource: "../src/Todo/todo-services.yaml" }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\Kernel: ~