name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build Docker images
        uses: docker/bake-action@v4
        with:
          pull: true
          load: true
          files: |
            compose.yaml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max
      -
        name: Start services
        run: |
          echo "services:" > compose.override.yaml
          echo "  nginx:" >> compose.override.yaml
          echo "    ports:" >> compose.override.yaml
          echo "      - '809:80'" >> compose.override.yaml
          docker compose -f compose.yaml -f compose.override.yaml up --wait --no-build -d
      -
        name: Install dependencies
        run: docker compose exec -T backend composer install
      -
        name: Check HTTP reachability
        run: curl -v --fail-with-body http://localhost:809/en/login
      -
        name: Create test database
        run: docker compose exec -T backend bin/console -e test doctrine:database:create
      -
        name: Run migrations
        run: docker compose exec -T backend bin/console -e test doctrine:migrations:migrate --no-interaction
      -
        name: Run PHPUnit
        run: docker compose exec -T backend bin/phpunit
      -
        name: Doctrine Schema Validator
        run: docker compose exec -T backend bin/console -e test doctrine:schema:validate
      -
        name: Cleanup override file
        run: rm -f override.yaml